name: travter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.28
  auth_repository:
    path: packages/auth_repository
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_repository:
    path: packages/data_repository
  firebase_core: ^2.1.0
  functionalities_repository:
    path: packages/functionalities_repository
  trackers:
    path: packages/trackers
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  get_it: ^7.1.3
  injectable: ^1.5.3
  intl: ^0.17.0
  sign_button: ^2.0.2
  # firebase_storage: ^10.3.4
  uuid: ^3.0.6
  rxdart: ^0.27.4
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  date_time_picker: ^2.1.0
  tuple: ^2.0.0
  cached_network_image: ^3.2.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner:
  change_app_package_name: ^1.0.0
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  freezed: ^2.0.3+1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  injectable_generator: ^1.4.1
  test: ^1.16.8

  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    -
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21