name: traveler
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  another_flushbar: ^1.10.28
  auth_repository:
    path: packages/auth_repository
  auto_route: ^4.0.1
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_core: ^1.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  get_it: ^7.1.3
  injectable: ^1.5.3
  intl: ^0.17.0
  sign_button: ^2.0.2

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.4.1
  test: ^1.16.8

  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/