// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBKUcrXbDUZNy0qY6lc8U597ZQLrAZG_w',
    appId: '1:705404755637:android:ead78ea60daf3eda4368fc',
    messagingSenderId: '705404755637',
    projectId: 'tiver-b47d6',
    storageBucket: 'tiver-b47d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZd61eoxCqMRmeePrI7wNJM_BWBJXzyko',
    appId: '1:705404755637:ios:91f327c33ac405264368fc',
    messagingSenderId: '705404755637',
    projectId: 'tiver-b47d6',
    storageBucket: 'tiver-b47d6.appspot.com',
    iosClientId: '705404755637-7peqlr3uojho554b1t6dule68tdcc3ts.apps.googleusercontent.com',
    iosBundleId: 'com.tiver.app',
  );
}
