// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Njdrn6wFjkEa5ZABMQydZvLniMKvUsU',
    appId: '1:923667026926:android:449c2e8972d6946b3c74ff',
    messagingSenderId: '923667026926',
    projectId: 'traveler-26793',
    storageBucket: 'traveler-26793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkuqEzGkrNjPdDLJQ4XaZKPlQ1BOVSomg',
    appId: '1:923667026926:ios:462fcfbe4103a03a3c74ff',
    messagingSenderId: '923667026926',
    projectId: 'traveler-26793',
    storageBucket: 'traveler-26793.appspot.com',
    androidClientId:
        '923667026926-8i8b9prkgl62q23afp7lpgbptdtagbnn.apps.googleusercontent.com',
    iosClientId:
        '923667026926-kncp943lspa5k6njlb6hseqvj7d08hfo.apps.googleusercontent.com',
    iosBundleId: 'com.traveler.app',
  );
}
