name: auth_repository

on:
  pull_request:
    paths:
      - "packages/auth_repository/**"
      - ".github/workflows/auth_repository.yml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/auth_repository