name: functionalities_repository.yml

on:
  push:
    paths:
      - "packages/functionalities_repository.yml/**"
      - ".github/workflows/functionalities_repository.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze lib

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random